# Generated by Django 4.2.7 on 2024-05-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_updated_at_alter_job_location_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
